# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5e88831f9caf5485b2398c2013cb6028f6fe4092d9c6421ebcf376d33fee0482f5027e8130b32a6b0324c0e42ae529152826c4aa75fc39fc7fcacaebc972a8

test:
  secret_key_base: aa0286b8234d046b99d5a479bc7780a05399c86a655a79cde82838038aa09b177a02c11a9663541b78387c9560b25b7f68a5851aab531f3678bf3ba96530c4ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
